-- No. 1
-- a.
ALTER TABLE BUKU
ADD BU_DURASI_PINJAM varchar(10);

-- b.
UPDATE BUKU
SET BU_DURASI_PINJAM = 2
WHERE BU_PENERBIT = 'Gramedia'

-- No. 2
UPDATE TRANSAKSI_PEMINJAMAN
SET TP_DENDA = 15000
WHERE TP_AN_ID = 58

-- No. 3
SELECT AN_NAMA FROM ANGGOTA
WHERE (AN_TGL_REGIS < DATE '2022-03-01') AND (AN_TGL_REGIS > '2022-01-31')

-- No. 4
SELECT PETUGAS.PE_NAMA FROM PETUGAS JOIN AKSES
ON (PETUGAS.PE_AK_ID = AKSES.AK_ID)
WHERE AKSES.AK_ID IN (3101)

-- No.  5
SELECT BU_JUDUL FROM BUKU
WHERE BU_STOK < 4

-- No. 6
SELECT COUNT(TP_TGL_KEMBALI) FROM TRANSAKSI_PEMINJAMAN
WHERE (TP_TGL_KEMBALI = DATE '2022-11-27')

-- No. 7

-- N0. 8
SELECT BU_JUDUL JOIN TRANSAKSI_PEMINJAMAN 